{"name": "Создание курьера с существующим логином - получено сообщение об ошибке", "status": "passed", "start": 1719935469901, "stop": 1719935470030, "uuid": "b0f6d74b-82d0-45f3-a465-94cc304e356a", "historyId": "46b414fe68124d7907fc25ecd16abfb0", "testCaseId": "46b414fe68124d7907fc25ecd16abfb0", "fullName": "tests.test_courier.TestCreationCourier#test_create_courier_existing_login_creation_error", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_courier"}, {"name": "subSuite", "value": "TestCreationCourier"}, {"name": "host", "value": "MacBook-Air-Vladislav.local"}, {"name": "thread", "value": "87558-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_courier"}]}